language: node_js
node_js:
- '4'
- stable
notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/54f8a1e753f859f5ca1a
    on_start: never
    on_failure: change
deploy:
  provider: npm
  email: hello@trailsjs.io
  api_key:
    secure: jTjQ0sraQ1OoLY8ru8KU6CVTvttOYNgwTjGZ+aEr4NHysM6P4h8M66+hu820MH7VJjeEYKRsDqsgbTKEQAxAUzuhFpqPdmw44w2wtLngM3mlPbTF+c6sPCYPl0TjUv8g/bG3rnZrWUiOxW6HrNCQkisuc3jjV8ScBw1ZJ9BEK8wbWISN9YpAz5PXZUaS56gB28GO9v/bJC+0Mfk0l/yuKpfPzBzU3//+4gCCNuaBEGMnSBcHM8vACbXDn68MYWPkWWxSkUm+r6XoWqNlXoOoK2ZIyoHyA8wFgxTtcmLRe19NiCi6zPdID0eGWKybYImdOFeoMPDK2F5niRNopyBckjW/4o3qt6wHGa5yD1/Bnm1Su+ErTLFpWXgdkT1WhWu9UPN98yolPc2ULaTUaCjw8TFpYs2UnT8+D/8nNg59oHmNpclkxtTNP4xBpC28eU8pC/jeh13i55lUM5EmIVQr4P4f2lK6wbSpE2gpV2lmS8SYKBDWCFVpl8Xlk5NmJu1jMp7VH+Ja5NygS1uxk00mufJQuJueqsUVliiAuXvx39kHAtzO5wkV67s/1Ck6lDcKoQwT81yn2W1fYhOJtWx3OHBpazmnlDe5sBT97fi8iCyJODl1kKzWKwWAioMMG92N/i1rLillk9y/HxgVVDGoW/EeP8Lc73n8NA3kgoSObOU=
  on:
    tags: true
    repo: trailsjs/trailpack-repl
