language: node_js
node_js:
- '4'
- stable

notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/54f8a1e753f859f5ca1a
    on_start: never
    on_failure: change

deploy:
  provider: npm
  email: hello@trailsjs.io
  api_key:
    secure: UT9vSbf1khaaoE7e8za+mw/k8PI5NxIbAgFKsdpkKodHi9z2gUGEUkOdBhHSsiV9pA5FT58F726jHb1hiD/CfSlDx8njDMXM2wOdSc3wfgNozuI9xKGHS3pzie+lAIStmYfAGDdQ5puxyiE9uAmhTb8RpfPbXJ7ffCe39H3i2K2Q/9tZ3LNZ5cTlKnbHg7I5dH56i24jVBiEalWtS3IfRGJRoQbGI4ZOJWoWsC/tsIUyKbDjOH2Erun0mBEajZEdLUDut4DyFTWfWjnZiie9AOzLR2WaH9eXHW0mYqinAQ2vbNSfsvIiScDzSVPBItX4HcFR5qa0AW8pxBRhDtVgH96Iq+GtqdjIXSO2nByTLzH7xVxmQkMBBcF6AOiahV6R/IOdA/Gq7lUm8X1Nq+WpVSy+wy2YEpdXkziNqdftLqrufRadgFPad3yu2VBMH024fPP1q9EZvr/OTrGc3pF0dcl7GBm/NAXjkpA85m6aWHT2voiB86ZidZpsEfA9J2KiBOcfKXqgnWBFQWFVimwXZgKKdktaCAf/Q+R8GWq6wpeXgh70/VMblXqN7KnmGJ0N91L1UfVIousKiKOKas546J6UU9fhXtdHJ0NiQM/H/OgH2SUpDfBNycrzJ+GZdGZ8jn/hhEXB5eG5ifk+Iv9u8cZpr2URBgq8OsAHUxYU0p0=
  on:
    tags: true
    repo: trailsjs/trailpack-repl
    all_branches: true
